const bankNames = [
    { name: "Agrani Bank Ltd.", type: "Public" },
    { name: "Bangladesh Development Bank Ltd.", type: "Public" },
    { name: "Basic Bank Ltd.", type: "Public" },
    { name: "Janata Bank Ltd.", type: "Public" },
    { name: "Rupali Bank Ltd.", type: "Public" },
    { name: "Sonali Bank Ltd.", type: "Public" },
    { name: "AB Bank Ltd.", type: "Private" },
    { name: "Bangladesh Commerce Bank Ltd.", type: "Private" },
    { name: "Bank Asia Ltd.", type: "Private" },
    { name: "BRAC Bank Ltd.", type: "Private" },
    { name: "City Bank Ltd.", type: "Private" },
    { name: "Dhaka Bank Ltd.", type: "Private" },
    { name: "Dutch-Bangla Bank Ltd.", type: "Private" },
    { name: "Eastern Bank Ltd.", type: "Private" },
    { name: "IFIC Bank Ltd.", type: "Private" },
    { name: "Jamuna Bank Ltd.", type: "Private" },
    { name: "Meghna Bank Ltd.", type: "Private" },
    { name: "Mercantile Bank Ltd.", type: "Private" },
    { name: "Midland Bank Ltd.", type: "Private" },
    { name: "Modhumoti Bank Ltd.", type: "Private" },
    { name: "Mutual Trust Bank Ltd.", type: "Private" },
    { name: "National Bank Ltd.", type: "Private" },
    { name: "National Credit & Commerce Bank Ltd.", type: "Private" },
    { name: "NRB Bank Ltd.", type: "Private" },
    { name: "NRB Commercial Bank Ltd.", type: "Private" },
    { name: "One Bank Ltd.", type: "Private" },
    { name: "Premier Bank Ltd.", type: "Private" },
    { name: "Prime Bank Ltd.", type: "Private" },
    { name: "Pubali Bank Ltd.", type: "Private" },
    { name: "Shimanto Bank Ltd.", type: "Private" },
    { name: "South Bangla Agriculture & Commerce Bank Ltd.", type: "Private" },
    { name: "Southeast Bank Ltd.", type: "Private" },
    { name: "Standard Bank Ltd.", type: "Private" },
    { name: "Trust Bank Ltd.", type: "Private" },
    { name: "United Commercial Bank Ltd.", type: "Private" },
    { name: "Uttara Bank Ltd.", type: "Private" },
    { name: "Al-Arafah Islami Bank Ltd.", type: "Islamic" },
    { name: "EXIM Bank Ltd.", type: "Islamic" },
    { name: "First Security Islami Bank Ltd.", type: "Islamic" },
    { name: "ICB Islamic Bank Ltd.", type: "Islamic" },
    { name: "Islami Bank Bangladesh Ltd.", type: "Islamic" },
    { name: "Shahjalal Islami Bank Ltd.", type: "Islamic" },
    { name: "Social Islami Bank Ltd.", type: "Islamic" },
    { name: "Union Bank Ltd.", type: "Islamic" },
    { name: "Bank Al-Falah Ltd.", type: "Foreign" },
    { name: "Citibank N.A", type: "Foreign" },
    { name: "Commercial Bank of Ceylon", type: "Foreign" },
    { name: "Habib Bank Ltd.", type: "Foreign" },
    { name: "HSBC", type: "Foreign" },
    { name: "National Bank of Pakistan", type: "Foreign" },
    { name: "Standard Chartered Bank", type: "Foreign" },
    { name: "State Bank of India", type: "Foreign" },
    { name: "Woori Bank", type: "Foreign" },
    { name: "Bangladesh Krishi Bank", type: "Specialized" },
    { name: "Rajshahi Krishi Unnayan Bank", type: "Specialized" },
    { name: "Ansar VDP Unnayan Bank", type: "Specialized" },
    { name: "Grameen Bank", type: "Specialized" }
  ];
  
  export default bankNames;
  